### ISSUE TITLE
گردونه شانس

### ISSUE THREAD

**Issue by mahshid-dd** [farzad-sedaghatbin/spinnerV1#244]
بعد از اینکه پاپاپ اخطار میاد که سهمیه ی امروز شما تمام شده است و روی دکمه ی باشه میزنی باید برگرده صفحه ی قبل اما الان همونجا میمونه

**Comment by farzad-sedaghatbin** [comment]
اینکار بدتر گیجشون میکنه.بازیای مشابه مثل کوییز و بقیه اینکارو نمیکنن
