### ISSUE TITLE
نوتیفیکیشن نوبت بازی

### ISSUE THREAD

**Issue by farzad-sedaghatbin** [farzad-sedaghatbin/spinnerV1#76]

**Comment by farzad-sedaghatbin** [comment]
https://ionicframework.com/docs/native/phonegap-local-notification/

**Comment by farzad-sedaghatbin** [comment]
servero zadam 1/turn vorodi username

**Comment by omiddagala** [comment]
adrese logo ro in gozashtam : 
http://dagala.ir/img/logo.png
age nist bezar ke too local notification biad
